// Generated by CoffeeScript 1.3.3
var $;

$ = jQuery;

$('a[rel="external"]').attr('target', '_blank');

$(".fancybox").fancybox({
  maxWidth: 800,
  maxHeight: 600,
  fitToView: false,
  autoSize: false,
  padding: 0,
  closeClick: false,
  openEffect: 'fade',
  closeEffect: 'fade'
});
