// Generated by CoffeeScript 1.3.3
(function() {
  var init;

  init = function() {
    $('a[rel="external"]').attr('class', '_blank');
    return true;
  };

  jQuery(function() {
    var $;
    $ = jQuery;
    init();
    return false;
  });

}).call(this);
